name: parking

services:
  web:
    build: .
    container_name: webcont
    restart: unless-stopped
    networks:
      - net

  ngx:
    image: nginx:1.29.4-alpine-slim
    container_name: ngxcont
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/log:/var/log/nginx
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      web:
        condition: service_healthy
    networks:
      - net


networks:
  net:
    driver: bridge